# CARISMA and CANOPUS

Short notebook demonstrating the CARISMA and CANOPUS modules.

CANOPUS data is similar to CARISMA data and hosted by the University of Alberta. Data must be downloaded from the website before loading as a CANOPUS data server does not exist.

In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#%matplotlib notebook

In [6]:
import os, sys
pth = '../'
sys.path.append(os.path.dirname(pth))

In [7]:
# import modules
import gmag.arrays.carisma as carisma
from gmag import utils
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
# list the local and remote file locations and file names
# used for download and loading data
fl = carisma.list_files('GILL','2012-01-01',ndays=4)
fl.head()

,date,fname,dir,hdir
0,2012-01-01,20120101GILL.F01.gz,D:\scratch\magnetometer\magnetometer\CARISMA\2...,http://data.carisma.ca/FGM/1Hz/2012/01/01/
1,2012-01-02,20120102GILL.F01.gz,D:\scratch\magnetometer\magnetometer\CARISMA\2...,http://data.carisma.ca/FGM/1Hz/2012/01/02/
2,2012-01-03,20120103GILL.F01.gz,D:\scratch\magnetometer\magnetometer\CARISMA\2...,http://data.carisma.ca/FGM/1Hz/2012/01/03/
3,2012-01-04,20120104GILL.F01.gz,D:\scratch\magnetometer\magnetometer\CARISMA\2...,http://data.carisma.ca/FGM/1Hz/2012/01/04/

In [9]:
# download a single station of data
carisma.download('GILL','2021-02-09',ndays=1)

Downloading http://data.carisma.ca/FGM/1Hz/2021/02/09/20210209GILL.F01.gz

In [10]:
# load data and meta data from 2 sites for a single day
c_dat, c_meta=carisma.load(['ISLL','GILL'],'2019-01-04',ndays=1,drop_flag=False)

Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2019/01/04/20190104ISLL.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2019\01\04\20190104ISLL.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2019/01/04/20190104GILL.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2019\01\04\20190104GILL.F01.gz

In [11]:
# show the loaded DataFrame
c_dat.head()

,ISLL_X,ISLL_Y,ISLL_Z,ISLL_flag,GILL_X,GILL_Y,GILL_Z,GILL_flag,ISLL_H,ISLL_D,GILL_H,GILL_D
t,,,,,,,,,,,,
2019-01-04 00:00:00,12098.819,52.047,57679.853,.,11474.709,-373.669,58241.237,.,12098.795448,57.260800,11478.297248,-239.306193
2019-01-04 00:00:01,12098.841,52.034,57679.850,.,11474.700,-373.672,58241.184,.,12098.817453,57.247810,11478.288283,-239.309298
2019-01-04 00:00:02,12098.844,52.041,57679.831,.,11474.800,-373.600,58241.197,.,12098.820450,57.254811,11478.387433,-239.236132
2019-01-04 00:00:03,12098.844,52.047,57679.825,.,11474.728,-373.703,58241.150,.,12098.820448,57.260811,11478.316644,-239.339968
2019-01-04 00:00:04,12098.847,52.059,57679.819,.,11474.797,-373.637,58241.178,.,12098.823443,57.272812,11478.384867,-239.273164

In [12]:
# show the meta data
c_meta
c_meta['Coordinates'][0]

,array,code,name,latitude,longitude,cgm_latitude,cgm_longitude,declination,lshell,mlt_midnight,mlt_ut,year,Time Resolution,Coordinates,PI,Institution
0,CARISMA,ISLL,Island Lake,53.856,265.34,63.02717,335.6151,-0.024691,4.860886,6.879090,17.12091,2019,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
1,CARISMA,GILL,Gillam,56.376,265.36,65.40524,335.3998,-0.670791,5.772988,6.893449,17.10655,2019,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta

'Geographic North - X, East - Y, Vertical Down - Z, Geomagnetic North - H, East- D, Vertical Down - Z'

In [13]:
# Read in all Carisma Data for a particular day
car_stn = utils.load_station_coor(param='CARISMA',col='array')
c_dat2, c_meta2 = carisma.load(list(car_stn['code']),'2020-01-02')
c_meta2

Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102ANNA.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102ANNA.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102BACK.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102BACK.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102CONT.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102CONT.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102DAWS.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102DAWS.F01.gz
Downloading Data:
Error in request: 404
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102ESKI.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102ESKI.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102FCHP.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102FCHP.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102FCHU.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102FCHU.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102FSIM.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102FSIM.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102FSMI.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102FSMI.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102GILL.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102GILL.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102GULL.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102GULL.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102ISLL.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102ISLL.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102LGRR.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102LGRR.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102MCMU.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102MCMU.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102MSTK.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102MSTK.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102NORM.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102NORM.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102OSAK.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102OSAK.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102OXFO.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102OXFO.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102PINA.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102PINA.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102POLS.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102POLS.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102RABB.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102RABB.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102RANK.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102RANK.F01.gz
Downloading Data:
Error in request: 404
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102SACH.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102SACH.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102TALO.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102TALO.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102THRF.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102THRF.F01.gz
Downloading Data:
Downloading http://data.carisma.ca/FGM/1Hz/2020/01/02/20200102VULC.F01.gz
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102VULC.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102WEYB.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102WEYB.F01.gz
Downloading Data:
Error in request: 403
Loading: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102WGRY.F01.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CARISMA\2020\01\02\20200102WGRY.F01.gz

,array,code,name,latitude,longitude,cgm_latitude,cgm_longitude,declination,lshell,mlt_midnight,mlt_ut,year,Time Resolution,Coordinates,PI,Institution
0,CARISMA,DAWS,Dawson City,64.048,220.890,65.91730,276.6378,18.993610,6.005693,10.784470,13.21553,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
1,CARISMA,FCHU,Fort Churchill,58.763,265.920,67.56386,335.5234,-1.639292,6.865333,6.858766,17.14123,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
2,CARISMA,FSIM,Fort Simpson,61.756,238.770,66.96090,297.0385,18.491190,6.529031,9.424425,14.57557,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
3,CARISMA,FSMI,Fort Smith,60.017,248.050,66.84846,309.4577,14.230980,6.469216,8.596480,15.40352,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
4,CARISMA,GILL,Gillam,56.376,265.360,65.29900,334.9697,-0.359091,5.726519,6.895680,17.10432,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
5,CARISMA,GULL,Gull Lake,50.061,251.739,57.84788,316.8351,10.688430,3.531027,8.104652,15.89535,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
6,CARISMA,ISLL,Island Lake,53.856,265.340,62.92218,335.2026,0.196434,4.826087,6.880153,17.11985,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
7,CARISMA,MCMU,Fort McMurray,56.657,248.790,63.75269,311.4824,13.288060,5.112944,8.461500,15.53850,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
8,CARISMA,MSTK,Ministik Lake,53.351,247.026,60.28070,310.0774,13.611830,4.068855,8.555170,15.44483,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
9,CARISMA,NORM,Norman Wells,65.257,233.311,69.36080,288.8363,20.164310,8.048706,9.971241,14.02876,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
10,CARISMA,OSAK,Osakis,45.871,264.917,55.29608,335.1918,1.502838,3.085056,6.880872,17.11913,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
11,CARISMA,POLS,Polson,47.664,245.791,54.53471,309.8492,13.052930,2.970503,8.570381,15.42962,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
12,CARISMA,RABB,Rabbit Lake,58.222,256.320,66.26620,321.3955,8.043051,6.172971,7.800626,16.19937,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
13,CARISMA,RANK,Rankin Inlet,62.824,267.890,71.41072,338.0219,-5.834986,9.840397,6.692203,17.30780,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta
14,CARISMA,VULC,Vulcan,50.367,247.020,57.38344,310.7698,13.062470,3.441911,8.509008,15.49099,2020,1.0,"Geographic North - X, East - Y, Vertical Down ...",Ian Mann,University of Alberta

In [14]:
# load some canopus data
import gmag.arrays.canopus as canopus
can_d, can_m=canopus.load('GILL','1995-06-23',ndays=1)
can_d.head()

Downloading Data:
Loading: D:\scratch\magnetometer\magnetometer\CANOPUS\1995\06\GILL\19950623GILL.MAG.gz
File does not exist: D:\scratch\magnetometer\magnetometer\CANOPUS\1995\06\GILL\19950623GILL.MAG.gz

TypeError: cannot unpack non-iterable NoneType object

In [ ]:
can_m